{"name": "test06[3-4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "self = <module_1.test_pytest.Test6 object at 0x10cfc8670>, result = 3\nactual_result = 4\n\n    @pytest.mark.parametrize('result,actual_result', list_test)\n    def test06(self, result, actual_result):\n>       assert result == actual_result\nE       assert 3 == 4\n\ntest_pytest.py:126: AssertionError"}, "parameters": [{"name": "result", "value": "3"}, {"name": "actual_result", "value": "4"}], "start": 1650499176731, "stop": 1650499176731, "uuid": "b3b7cad0-cc1c-4e0b-87bf-96bba5e13981", "historyId": "0e5fbe8e970a1147fffc1cfa8a40880b", "testCaseId": "d981e8d40435ac38e24e65f3ba05b9c0", "fullName": "test_pytest.Test6#test06", "labels": [{"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Test6"}, {"name": "host", "value": "li-MacBook-Pro"}, {"name": "thread", "value": "1076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}